const IMAGES_FILE_EXTENSION = '.webp'
const SOUNDS_FILE_EXTENSION = '.mp3'

const SOUNDS_SELECTOR = '.sounds'
const IMAGES_SELECTOR = '.images'

export {
    IMAGES_FILE_EXTENSION, SOUNDS_FILE_EXTENSION,
    SOUNDS_SELECTOR, IMAGES_SELECTOR,
}
